AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.1
  Exclude:
    - 'lib/graphql/language/lexer.rb'
    - 'lib/graphql/language/parser.rb'
    - 'gemfiles/**/*'
    - 'spec/tmp/**/*'

# def ...
# end
Lint/DefEndAlignment:
  EnforcedStyleAlignWith: def

# value = if
#   # ...
# end
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/IndentationWidth:
  Width: 2

Style/LambdaCall:
  EnforcedStyle: call

Style/LeadingCommentSpace:
  Enabled: true

Style/MethodName:
  EnforcedStyle: snake_case

Style/WordArray:
  EnforcedStyle: brackets
