AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.1
  Exclude:
  - 'lib/graphql/language/lexer.rb'
  - 'lib/graphql/language/parser.rb'

# value = do_something
# if value # ...
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# def ...
# end
Lint/DefEndAlignment:
  AlignWith: def

# value = if
#   # ...
# end
Lint/EndAlignment:
  AlignWith: variable

Metrics/ClassLength:
  CountComments: false
  Max: 120

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/DeprecatedHashMethods:
  Enabled: true

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/IndentationWidth:
  Width: 2

Style/LambdaCall:
  EnforcedStyle: call

Style/LeadingCommentSpace:
  Enabled: true

Style/MethodName:
  EnforcedStyle: snake_case

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  EnforcedStyle: brackets
