require:
  - ./cop/none_without_block_cop
  - ./cop/no_focus_cop
  - ./lib/graphql/rubocop/graphql/default_null_true
  - ./lib/graphql/rubocop/graphql/default_required_true
  - ./cop/context_is_passed_cop

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'lib/graphql/language/lexer.rb'
    - 'lib/graphql/language/parser.rb'
    - 'gemfiles/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/integration/tmp/**/*'
    - 'spec/fixtures/cop/*.rb'

ContextIsPassedCop:
  Exclude:
    - 'spec/**/*'
    # Legacy-related:
    - 'lib/graphql/*_type.rb'
    - 'lib/graphql/define/**/*.rb'
    - 'lib/graphql/relay/**/*'
    - 'lib/graphql/schema/traversal.rb'
    - 'lib/graphql/schema/possible_types.rb'
    - 'lib/graphql/schema/validation.rb'
    - 'lib/graphql/compatibility/**/*'
    - 'lib/graphql/static_validation/type_stack.rb'
    # AST-related:
    - 'lib/graphql/schema/build_from_definition.rb'
    - 'lib/graphql/language/printer.rb'
    # Build-time, not runtime:
    - 'lib/graphql/schema/addition.rb'
    - 'lib/graphql/schema/introspection_system.rb'
    # Methods from generators
    - 'lib/generators/graphql/type_generator.rb'

# def ...
# end
Layout/DefEndAlignment:
  EnforcedStyleAlignWith: def

# value = if
#   # ...
# end
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/UselessAssignment:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Style/LambdaCall:
  EnforcedStyle: call

Layout/LeadingCommentSpace:
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case

Style/WordArray:
  EnforcedStyle: brackets

# ->(...) { ... }
Layout/SpaceInLambdaLiteral:
  Enabled: true # Default is "require_no_space"

GraphQL/DefaultNullTrue:
  Enabled: true

GraphQL/DefaultRequiredTrue:
  Enabled: true
