title: Your awesome title
baseurl:
url: "https://rmosolgo.github.io/graphql-ruby"

layouts_dir:  guides/_layouts

include:
  - guides/css

exclude:
  - "bin"
  - "vendor"
  - "spec"
  - "Gemfile*"
  - "CONTRIBUTING.md"
  - "Rakefile"
  - gemfiles
  - lib

# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  guides:
    output: true
    permalink: /:path
