title: GraphQL Ruby
baseurl: ""
url: "http://graphql-ruby.org"

exclude:
  - .gitignore

# Build settings
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
