name: CI Suite
on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: bundle exec rake rubocop
  system_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo BUNDLE_GEMFILE="spec/dummy/Gemfile" > $GITHUB_ENV
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
      working-directory: ./spec/dummy
    - run: |
        pwd
        ls
        bundle exec rails -v
        bundle exec rails test:system
      working-directory: ./spec/dummy
  test:
    strategy:
      matrix:
        gemfile: ["Gemfile", "gemfiles/rails_5.2.gemfile"]
    runs-on: ubuntu-latest
    steps:
    - run: echo BUNDLE_GEMFILE=${{ matrix.gemfile }} > $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake test
    - run: bundle exec rake test TESTING_LEGACY=1
      if: ${{ matrix.gemfile == 'Gemfile' }}
    - run: bundle exec rake js:all
      if: ${{ matrix.gemfile == 'Gemfile' }}
