name: Unit tests
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: bundle install
    - run: bundle exec rake rubocop
    - run: bundle exec rake test
    - run: bundle exec rake test TESTING_LEGACY=1
    - run: bundle exec rake test:js
    - run: BUNDLE_GEMFILE="gemfiles/mongoid_5.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/mongoid_6.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/mongoid_7.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_3.2.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_4.1.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_4.2.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_5.0.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_5.1.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_5.2.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_5.2_postgresql.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_6.0.gemfile" bundle install && bundle exec rake test
    - run: BUNDLE_GEMFILE="gemfiles/rails_master.gemfile" bundle install && bundle exec rake test
    - run: cd spec/dummy && bundle install && bundle exec rails test:system && cd ../..
