name: Publish Website
on:
  push:
    branches: [master]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install and publish
        with:
          env:
            ALGOLIA_API_KEY: {{ secrets.ALGOLIA_API_KEY }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake site:publish
