name: Publish Website
on:
  push:
    branches: [master]

permissions: {}
jobs:
  build:
    permissions:
      contents: write # for git push (s0/git-publish-subdir-action)
    name: Publish Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Checkout GitHub pages branch
        uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Build HTML, reindex
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          bundle exec rake site:fetch_latest site:build_doc site:update_search_index site:clean_html site:build_html
      - name: Commit changes as last committer
        run: |
          git config --global user.name "%(git log --format="%aN" -n 1)"
          git config --global user.email "%(git log --format="%aE" -n 1)"
          bundle exec rake site:commit_changes
      - name: Deploy to GitHub pages via gh-pages branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
